apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: event-driven-template
spec:
  params:
    - name: git-revision
      description: The git revision (commit SHA)
    - name: git-repo-url
      description: The git repository URL
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: event-driven-pipeline
      spec:
        pipelineref:
          name: event-driven-pipeline
        serviceAccountName: pipeline
        params:
          - name: url
            value: $(tt.params.git-repo-url)
          - name: revision
            value: $(tt.params.git-revision)
        workspaces:
          - name: shared-workspace
            persistentVolumeClaim: event-driven-pvc
